### ISSUE TITLE
InvalidDataException while running

### ISSUE THREAD

**Issue by Lijoosh** [PathriK/GaanaExtractor#1]
Getting the following exception while running the jar file.
com.mpatric.mp3agic.InvalidDataException: No mpegs frames found
at com.mpatric.mp3agic.Mp3File.init(Mp3File.java:83)
    at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:68)
    at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:59)
    at in.pathri.gaanaextractor.MainExtractor.copyConvert(MainExtractor.java:69)
    at in.pathri.gaanaextractor.MainExtractor.extract(MainExtractor.java:56)
    at in.pathri.gaanaextractor.MainExtractor.main(MainExtractor.java:42)

**Comment by PathriK** [comment]
Please let me know the file on which you are using the tool. Possible to send me the files that you are trying to convert?

**Comment by PathriK** [comment]
Release 1.2 must have fixed the issue. Please check and let me know when possible.
Thanks

**Comment by PathriK** [comment]
Hi
After a long time have released a new version....
https://github.com/PathriK/GaanaExtractor/releases/tag/v2.0-BETA
Now it should be able to convert nearly all the songs..
Please try it out and let me know if the issues are fixed..

**Comment by Lijoosh** [comment]
Thank you Keerthi.

I will try it and will post the feedback.

Regards,
Lijoosh

**Comment by PathriK** [comment]
@Lijoosh . Can you please let me know if the issue is fixed?
