### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mathan7** [PathriK/GaanaExtractor#17]
**********Gaana Extractor**********
**NOTE**:Songs Source Directory::h:/New folder (3)/devaram- suntharar
**NOTE**:Songs will be grouped into Folders based on Album names

Converting:: \688718
Catching
org.jaudiotagger.audio.exceptions.CannotReadException: No Reader associated with this extension:
        at org.jaudiotagger.audio.AudioFileIO.readFileMagic(AudioFileIO.java:387) ~[GaanaExtractor-2.6-SNAPSHOT.jar:?]
        at org.jaudiotagger.audio.AudioFileIO.readMagic(AudioFileIO.java:176) ~[GaanaExtractor-2.6-SNAPSHOT.jar:?]
        at in.pathri.gaana.extractor.MainExtractor.copyConvert(MainExtractor.java:123) [GaanaExtractor-2.6-SNAPSHOT.jar:?]
        at in.pathri.gaana.extractor.MainExtractor.extract(MainExtractor.java:107) [GaanaExtractor-2.6-SNAPSHOT.jar:?]
        at in.pathri.gaana.extractor.MainExtractor.main(MainExtractor.java:82) [GaanaExtractor-2.6-SNAPSHOT.jar:?]

COMPLETED with ERRORS. Following are the details:

File Data Not Found :: NONE
File Read Error :: 688718
File Write Error :: NONE
File Tag Error ::NONE

**Comment by PathriK** [comment]
@mathan7 

Thanks for trying the utility. Can you mail me the complete log file and if possible the song file also for which you are getting error?

Thanks
